# CMake generated Testfile for 
# Source directory: D:/Project/Reversi/ReversiAI_Platform/Tests/unit
# Build directory: D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(UnitTests_Core "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/Debug/unit_tests_core.exe")
  set_tests_properties(UnitTests_Core PROPERTIES  LABELS "unit;core" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;93;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(UnitTests_Core "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/Release/unit_tests_core.exe")
  set_tests_properties(UnitTests_Core PROPERTIES  LABELS "unit;core" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;93;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(UnitTests_Core "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/MinSizeRel/unit_tests_core.exe")
  set_tests_properties(UnitTests_Core PROPERTIES  LABELS "unit;core" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;93;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(UnitTests_Core "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/RelWithDebInfo/unit_tests_core.exe")
  set_tests_properties(UnitTests_Core PROPERTIES  LABELS "unit;core" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;93;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
else()
  add_test(UnitTests_Core NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(UnitTests_AI "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/Debug/unit_tests_ai.exe")
  set_tests_properties(UnitTests_AI PROPERTIES  LABELS "unit;ai" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;101;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(UnitTests_AI "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/Release/unit_tests_ai.exe")
  set_tests_properties(UnitTests_AI PROPERTIES  LABELS "unit;ai" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;101;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(UnitTests_AI "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/MinSizeRel/unit_tests_ai.exe")
  set_tests_properties(UnitTests_AI PROPERTIES  LABELS "unit;ai" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;101;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(UnitTests_AI "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/RelWithDebInfo/unit_tests_ai.exe")
  set_tests_properties(UnitTests_AI PROPERTIES  LABELS "unit;ai" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;101;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
else()
  add_test(UnitTests_AI NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(UnitTests_Network "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/Debug/unit_tests_network.exe")
  set_tests_properties(UnitTests_Network PROPERTIES  LABELS "unit;network" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;113;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(UnitTests_Network "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/Release/unit_tests_network.exe")
  set_tests_properties(UnitTests_Network PROPERTIES  LABELS "unit;network" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;113;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(UnitTests_Network "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/MinSizeRel/unit_tests_network.exe")
  set_tests_properties(UnitTests_Network PROPERTIES  LABELS "unit;network" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;113;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(UnitTests_Network "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/RelWithDebInfo/unit_tests_network.exe")
  set_tests_properties(UnitTests_Network PROPERTIES  LABELS "unit;network" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;113;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
else()
  add_test(UnitTests_Network NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(UnitTests_Research "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/Debug/unit_tests_research.exe")
  set_tests_properties(UnitTests_Research PROPERTIES  LABELS "unit;research" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;154;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(UnitTests_Research "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/Release/unit_tests_research.exe")
  set_tests_properties(UnitTests_Research PROPERTIES  LABELS "unit;research" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;154;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(UnitTests_Research "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/MinSizeRel/unit_tests_research.exe")
  set_tests_properties(UnitTests_Research PROPERTIES  LABELS "unit;research" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;154;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(UnitTests_Research "D:/Project/Reversi/ReversiAI_Platform/build_test/Tests/unit/RelWithDebInfo/unit_tests_research.exe")
  set_tests_properties(UnitTests_Research PROPERTIES  LABELS "unit;research" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;154;add_test;D:/Project/Reversi/ReversiAI_Platform/Tests/unit/CMakeLists.txt;0;")
else()
  add_test(UnitTests_Research NOT_AVAILABLE)
endif()
