/**
 * @file mainwindow.cpp
 * @brief Main window implementation - V0.4.0 Refactored Version
 *
 * Refactoring content:
 * - Use GameController to manage game state
 * - Remove global variables
 * - Add signal/slot connections
 * - Keep core logic in paintEvent and mousePressEvent
 *
 * @reference QtReversi/code/chess/widget.cpp - Game rules and UI interaction
 * @reference MCTS-AI-Reversi/mainwindow.cpp - paintEvent() implementation preserved
 */

#include "mainwindow.h"
#include "ui_mainwindow.h"
#include "QPainter"
#include "QPixmap"
#include "QMouseEvent"
#include "QDebug"
#include "QTimer"

MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    // Initialize UI components
    initUI();

    // Create GameController
    gameController_ = std::make_unique<Reversi::GameController>(this);

    // Connect signals and slots
    setupConnections();

    // Keep resource loading (original code)
    background.load(":/rsc/board.png");
    black.load(":/rsc/black.png");
    white.load(":/rsc/white.png");
    hintwhite.load(":/rsc/whitepotential.png");
    hintblack.load(":/rsc/blackpotential.png");
    hintred.load(":/rsc/redpotential.png");

    // Connect button signals (using new slot functions)
    connect(ui->pushButton, &QPushButton::clicked,
            this, &MainWindow::onStartGameClicked);
}

MainWindow::~MainWindow() {
    delete ui;
}

void MainWindow::initUI() {
    // Keep original init() call
    // init() is defined in ui_mainwindow.h, generated by uic
}

void MainWindow::setupConnections() {
    // GameController signal/slot connections
    connect(gameController_.get(), &Reversi::GameController::gameStarted,
            this, &MainWindow::onGameStarted);
    connect(gameController_.get(), &Reversi::GameController::phaseChanged,
            this, &MainWindow::onPhaseChanged);
    connect(gameController_.get(), &Reversi::GameController::turnChanged,
            this, &MainWindow::onTurnChanged);
    connect(gameController_.get(), &Reversi::GameController::moveMade,
            this, &MainWindow::onMoveMade);
    connect(gameController_.get(), &Reversi::GameController::gameEnded,
            this, &MainWindow::onGameEnded);
    connect(gameController_.get(), &Reversi::GameController::aiThinkingStarted,
            this, &MainWindow::onAIThinkingStarted);
    connect(gameController_.get(), &Reversi::GameController::aiThinkingFinished,
            this, &MainWindow::onAIThinkingFinished);
    connect(gameController_.get(), &Reversi::GameController::aiStatsUpdated,
            this, &MainWindow::onAIStatsUpdated);
    connect(gameController_.get(), &Reversi::GameController::errorOccurred,
            this, &MainWindow::onErrorOccurred);
}

void MainWindow::paintEvent(QPaintEvent *event) {
    // Keep original implementation logic, only modify data source
    this->resize(600, 400);
    QPainter painter(this);
    painter.setRenderHint(QPainter::SmoothPixmapTransform, true);
    painter.drawPixmap(0, 0, 400, 400, background);

    // Get current state from GameController
    const Reversi::Board& board = gameController_->getBoard();
    Reversi::PlayerColor currentPlayer = gameController_->getCurrentPlayer();

    // Determine current piece color for valid move highlighting
    int tile = (currentPlayer == Reversi::PlayerColor::Black) ? 2 : 1;

    // Get valid moves and draw highlighting
    int markHaveDraw[8][8] = {0};
    auto validMoves = board.getValidMoves();
    for (const auto& move : validMoves) {
        markHaveDraw[move.row][move.col] = tile;
    }

    // Draw pieces and highlights
    // Note: board.at(row, col) - row is vertical (y), col is horizontal (x)
    // painter.drawPixmap(x, y) - x is horizontal, y is vertical
    // So use board.at(j, i) where j=row, i=col
    for (int i = 0; i < 8; i++) {  // i = col (horizontal)
        for (int j = 0; j < 8; j++) {  // j = row (vertical)
            int cellValue = board.at(j, i);  // j=row, i=col

            // Draw pieces
            if (cellValue == 1) {  // White
                painter.drawPixmap(0 + 50 * i, 0 + 50 * j, 50, 50, white);
            } else if (cellValue == 2) {  // Black
                painter.drawPixmap(0 + 50 * i, 0 + 50 * j, 50, 50, black);
            }

            // Draw valid move highlights
            // markHaveDraw[row][col] -> markHaveDraw[j][i]
            if (markHaveDraw[j][i] == 2) {  // Black's valid positions
                painter.drawPixmap(0 + 50 * i, 0 + 50 * j, 50, 50, hintblack);
            }
            if (markHaveDraw[j][i] == 1) {  // White's valid positions
                painter.drawPixmap(0 + 50 * i, 0 + 50 * j, 50, 50, hintwhite);
            }
        }
    }

    // Draw last move position (from GameController)
    // TODO: Need to add getLastMove() method in GameController
    // if (Last.x != -1) {
    //     painter.drawPixmap(0 + 50 * Last.x, 0 + 50 * Last.y, 50, 50, hintred);
    // }
}

void MainWindow::mousePressEvent(QMouseEvent *e) {
    // Check game state
    if (gameController_->getCurrentPhase() != Reversi::GamePhase::HumanTurn) {
        return;
    }

    // Coordinate conversion
    int row = e->y() / 50;
    int col = e->x() / 50;

    // Check if within board range
    if (row < 0 || row >= 8 || col < 0 || col >= 8) {
        return;
    }

    // Use GameController to handle moves
    gameController_->makeHumanMove(row, col);
}

void MainWindow::updateScoreDisplay() {
    // Get score from GameController
    const Reversi::Board& board = gameController_->getBoard();

    // Count pieces
    int blackCount = 0;
    int whiteCount = 0;

    for (int i = 0; i < 8; i++) {
        for (int j = 0; j < 8; j++) {
            int cellValue = board.at(i, j);
            if (cellValue == 2) blackCount++;
            else if (cellValue == 1) whiteCount++;
        }
    }

    // Update UI display
    if (ui->blabel) {
        ui->blabel->setText(QString::number(blackCount));
    }
    if (ui->wlabel) {
        ui->wlabel->setText(QString::number(whiteCount));
    }
}

// ============ Signal/Slot Implementation ============

void MainWindow::onStartGameClicked() {
    // Determine game mode: default is PvE (Player vs AI)
    Reversi::GameMode mode = Reversi::GameMode::PvE;
    Reversi::Difficulty difficulty = Reversi::Difficulty::MEDIUM;

    // Determine human player color (based on UI selection for who goes first)
    // AIchoice (AI First) -> AI moves first, human is white
    // playerchoice (Player First) -> Player moves first, human is black
    Reversi::PlayerColor humanColor;
    if (ui->AIchoice && ui->AIchoice->isChecked()) {
        humanColor = Reversi::PlayerColor::White;  // AI moves first, human is white
    } else if (ui->playerchoice && ui->playerchoice->isChecked()) {
        humanColor = Reversi::PlayerColor::Black;  // Player moves first, human is black
    } else {
        // Default to player going first
        humanColor = Reversi::PlayerColor::Black;
    }

    qDebug() << "MainWindow: Starting game, humanColor:" << (int)humanColor;

    // Start game (always PvE mode)
    gameController_->startNewGame(mode, humanColor, difficulty);
}

void MainWindow::onGameStarted(Reversi::GameMode mode, Reversi::PlayerColor humanColor) {
    qDebug() << "MainWindow: Game started, mode:" << (int)mode
             << "humanColor:" << (int)humanColor;
    updateScoreDisplay();
    repaint();
}

void MainWindow::onPhaseChanged(Reversi::GamePhase phase) {
    qDebug() << "MainWindow: Phase changed to" << (int)phase;

    // Update UI based on phase
    switch (phase) {
    case Reversi::GamePhase::Waiting:
        // Waiting for start state
        break;
    case Reversi::GamePhase::HumanTurn:
        // Human player turn
        break;
    case Reversi::GamePhase::AITurn:
        // AI turn, UI will show AI status
        break;
    case Reversi::GamePhase::GameOver:
        // Game over
        qDebug() << "MainWindow: Game Over";
        break;
    }

    repaint();
}

void MainWindow::onTurnChanged(Reversi::PlayerColor player) {
    qDebug() << "MainWindow: Turn changed to" << (int)player;
    updateScoreDisplay();
    repaint();
}

void MainWindow::onMoveMade(int row, int col, Reversi::PlayerColor player) {
    qDebug() << "MainWindow: Move made at" << row << col << "by player" << (int)player;
    updateScoreDisplay();
    repaint();
}

void MainWindow::onGameEnded(Reversi::GameResult result) {
    qDebug() << "MainWindow: Game ended, result:" << (int)result;

    QString resultText;
    switch (result) {
    case Reversi::GameResult::BlackWins:
        resultText = "Black Wins!";
        break;
    case Reversi::GameResult::WhiteWins:
        resultText = "White Wins!";
        break;
    case Reversi::GameResult::Draw:
        resultText = "Draw!";
        break;
    default:
        resultText = "Game Over";
        break;
    }

    // Display game result
    if (ui->AIGO) {
        ui->AIGO->setText(resultText);
    }

    updateScoreDisplay();
    repaint();
}

void MainWindow::onAIThinkingStarted(const QString& aiName) {
    qDebug() << "MainWindow: AI thinking started:" << aiName;
    if (ui->AIGO) {
        ui->AIGO->setText("AI Thinking: " + aiName);
    }
}

void MainWindow::onAIThinkingFinished(int row, int col) {
    qDebug() << "MainWindow: AI move finished at" << row << col;
    if (ui->AIGO) {
        ui->AIGO->setText(QString("AI Move: %1,%2").arg(col).arg(row));
    }
}

void MainWindow::onAIStatsUpdated(const Reversi::AIStats& stats) {
    // Update AI statistics display (if corresponding UI element exists)
    // TODO: Add AI statistics display UI element
    qDebug() << "MainWindow: AI stats - nodes:" << stats.nodesExplored
             << "time:" << stats.timeUsed.count() << "ms";
}

void MainWindow::onErrorOccurred(const QString& message) {
    qDebug() << "MainWindow: Error -" << message;
    // Can add error notification UI
}
