/**
 * @file PvPWindow.cpp
 * @brief Two-player battle window implementation
 *
 * Features:
 * - Two-player local battle
 * - Take turns with Black/White
 * - Undo functionality
 * - Back to menu functionality
 *
 * @reference QtReversi/code/chess/widget.cpp - Game rules and UI interaction
 */

#include "ui/PvPWindow.h"
#include "ui_pvpwindow.h"
#include "QPainter"
#include "QPixmap"
#include "QMouseEvent"
#include "QDebug"
#include "QIcon"

PvPWindow::PvPWindow(QWidget* parent)
    : QMainWindow(parent)
    , ui(new Ui::PvPWindow) {
    ui->setupUi(this);
    setWindowIcon(QIcon(":/rsc/black.png"));

    // Initialize UI components
    initUI();

    // Create GameController (PvP mode doesn't need AI)
    gameController_ = std::make_unique<Reversi::GameController>(this);

    // Connect signals and slots
    setupConnections();

    // Load resource files
    background.load(":/rsc/board.png");
    black.load(":/rsc/black.png");
    white.load(":/rsc/white.png");
    hintwhite.load(":/rsc/whitepotential.png");
    hintblack.load(":/rsc/blackpotential.png");
    hintred.load(":/rsc/redpotential.png");

    // Connect button signals
    connect(ui->pushButton, &QPushButton::clicked,
            this, &PvPWindow::onStartGameClicked);
    connect(ui->undoButton, &QPushButton::clicked,
            this, &PvPWindow::onUndoClicked);
    connect(ui->backButton, &QPushButton::clicked,
            this, &PvPWindow::onBackToMenuClicked);
}

PvPWindow::~PvPWindow() {
    delete ui;
}

void PvPWindow::initUI() {
    // init() is defined in ui_pvpwindow.h, generated by uic
}

void PvPWindow::setupConnections() {
    // GameController signal/slot connections (PvP doesn't need AI-related signals)
    connect(gameController_.get(), &Reversi::GameController::gameStarted,
            this, &PvPWindow::onGameStarted);
    connect(gameController_.get(), &Reversi::GameController::phaseChanged,
            this, &PvPWindow::onPhaseChanged);
    connect(gameController_.get(), &Reversi::GameController::turnChanged,
            this, &PvPWindow::onTurnChanged);
    connect(gameController_.get(), &Reversi::GameController::moveMade,
            this, &PvPWindow::onMoveMade);
    connect(gameController_.get(), &Reversi::GameController::gameEnded,
            this, &PvPWindow::onGameEnded);
    connect(gameController_.get(), &Reversi::GameController::errorOccurred,
            this, &PvPWindow::onErrorOccurred);
}

void PvPWindow::paintEvent(QPaintEvent* event) {
    this->resize(600, 400);
    QPainter painter(this);
    painter.setRenderHint(QPainter::SmoothPixmapTransform, true);
    painter.drawPixmap(0, 0, 400, 400, background);

    // Get current state from GameController
    const Reversi::Board& board = gameController_->getBoard();
    Reversi::PlayerColor currentPlayer = gameController_->getCurrentPlayer();

    // Determine current piece color for valid move highlighting
    int tile = (currentPlayer == Reversi::PlayerColor::Black) ? 2 : 1;

    // Get valid moves and draw highlighting
    int markHaveDraw[8][8] = {0};
    auto validMoves = board.getValidMoves();
    for (const auto& move : validMoves) {
        markHaveDraw[move.row][move.col] = tile;
    }

    // Draw pieces and highlights
    for (int i = 0; i < 8; i++) {  // i = col (horizontal)
        for (int j = 0; j < 8; j++) {  // j = row (vertical)
            int cellValue = board.at(j, i);  // j=row, i=col

            // Draw pieces
            if (cellValue == 1) {  // White
                painter.drawPixmap(0 + 50 * i, 0 + 50 * j, 50, 50, white);
            } else if (cellValue == 2) {  // Black
                painter.drawPixmap(0 + 50 * i, 0 + 50 * j, 50, 50, black);
            }

            // Draw valid move highlighting
            if (markHaveDraw[j][i] == 2) {  // Black's valid positions
                painter.drawPixmap(0 + 50 * i, 0 + 50 * j, 50, 50, hintblack);
            }
            if (markHaveDraw[j][i] == 1) {  // White's valid positions
                painter.drawPixmap(0 + 50 * i, 0 + 50 * j, 50, 50, hintwhite);
            }
        }
    }
}

void PvPWindow::mousePressEvent(QMouseEvent* e) {
    // Check game state (only HumanTurn in two-player mode)
    if (gameController_->getCurrentPhase() != Reversi::GamePhase::HumanTurn) {
        return;
    }

    // Coordinate conversion
    int row = e->y() / 50;
    int col = e->x() / 50;

    // Check if within board range
    if (row < 0 || row >= 8 || col < 0 || col >= 8) {
        return;
    }

    // Use GameController to handle moves
    gameController_->makeHumanMove(row, col);
}

void PvPWindow::updateScoreDisplay() {
    // Get score from GameController
    const Reversi::Board& board = gameController_->getBoard();

    // Count pieces
    int blackCount = 0;
    int whiteCount = 0;

    for (int i = 0; i < 8; i++) {
        for (int j = 0; j < 8; j++) {
            int cellValue = board.at(i, j);
            if (cellValue == 2) blackCount++;
            else if (cellValue == 1) whiteCount++;
        }
    }

    // Update UI display
    if (ui->blabel) {
        ui->blabel->setText(QString::number(blackCount));
    }
    if (ui->wlabel) {
        ui->wlabel->setText(QString::number(whiteCount));
    }
}

void PvPWindow::onStartGameClicked() {
    // PvP mode: Black moves first, player 1 is Black, player 2 is White
    Reversi::GameMode mode = Reversi::GameMode::PvP;
    Reversi::PlayerColor humanColor = Reversi::PlayerColor::Black;  // Player 1 moves first
    Reversi::Difficulty difficulty = Reversi::Difficulty::MEDIUM;   // PvP doesn't need AI

    qDebug() << "PvPWindow: Starting PvP game";

    // Start game
    gameController_->startNewGame(mode, humanColor, difficulty);
}

void PvPWindow::onUndoClicked() {
    // Undo functionality - undo last move
    qDebug() << "PvPWindow: Undo clicked";
    gameController_->undoMove();
    updateScoreDisplay();
    repaint();
}

void PvPWindow::onGameStarted(Reversi::GameMode mode, Reversi::PlayerColor humanColor) {
    qDebug() << "PvPWindow: Game started, mode:" << (int)mode
             << "first player:" << (int)humanColor;
    updateScoreDisplay();
    repaint();
}

void PvPWindow::onPhaseChanged(Reversi::GamePhase phase) {
    qDebug() << "PvPWindow: Phase changed to" << (int)phase;
    repaint();
}

void PvPWindow::onTurnChanged(Reversi::PlayerColor player) {
    qDebug() << "PvPWindow: Turn changed to" << (int)player;

    // Update current turn display
    if (ui->turnLabel) {
        QString turnText = (player == Reversi::PlayerColor::Black) ?
                           "Current Turn: Black" : "Current Turn: White";
        ui->turnLabel->setText(turnText);
    }

    updateScoreDisplay();
    repaint();
}

void PvPWindow::onMoveMade(int row, int col, Reversi::PlayerColor player) {
    qDebug() << "PvPWindow: Move made at" << row << col << "by player" << (int)player;
    updateScoreDisplay();
    repaint();
}

void PvPWindow::onGameEnded(Reversi::GameResult result) {
    qDebug() << "PvPWindow: Game ended, result:" << (int)result;

    QString resultText;
    switch (result) {
    case Reversi::GameResult::BlackWins:
        resultText = "Black Wins!";
        break;
    case Reversi::GameResult::WhiteWins:
        resultText = "White Wins!";
        break;
    case Reversi::GameResult::Draw:
        resultText = "Draw!";
        break;
    default:
        resultText = "Game Over";
        break;
    }

    // Display game result
    if (ui->turnLabel) {
        ui->turnLabel->setText(resultText);
    }

    updateScoreDisplay();
    repaint();
}

void PvPWindow::onErrorOccurred(const QString& message) {
    qDebug() << "PvPWindow: Error -" << message;
}

void PvPWindow::onBackToMenuClicked() {
    emit backToMenu();
}

